### ISSUE TITLE
yarn v4 support

### ISSUE THREAD

**Issue by lizthegrey** [heroku/heroku-buildpack-nodejs#1010]
**Is your enhancement request related to a problem? Please describe.**
While the new prune plugin works great on yarn 2/3, it fails on yarn 4:

```
       Running 'yarn heroku prune'
       Type Error: r.Command.Path is not a function (when initializing @yarnpkg/plugin-prune-dev-dependencies, defined in <environment>)
       at /tmp/buildpack9a0bK/yarn2-plugins/prune-dev-dependencies/bundles/@yarnpkg/plugin-prune-dev-dependencies.js:5:1353
       at factory (/tmp/buildpack9a0bK/yarn2-plugins/prune-dev-dependencies/bundles/@yarnpkg/plugin-prune-dev-dependencies.js:5:1438)
       at ve (/app/.yarn/releases/yarn-4.0.0-rc.6.cjs:135:21634)
       at Rm (/app/.yarn/releases/yarn-4.0.0-rc.6.cjs:134:30693)
       at ee (/app/.yarn/releases/yarn-4.0.0-rc.6.cjs:135:21614)
       at Function.find (/app/.yarn/releases/yarn-4.0.0-rc.6.cjs:135:21835)
       at async s (/app/.yarn/releases/yarn-4.0.0-rc.6.cjs:378:2549)
       at async r (/app/.yarn/releases/yarn-4.0.0-rc.6.cjs:378:2152)
```

**Describe the solution you'd like**
The module will need to be updated to use the updated Yarn plugin API.

**Comment by colincasey** [comment]
This has been fixed in #1040 and released with v200

**Comment by lizthegrey** [comment]
Omg thank you!!!!!

**Comment by lizthegrey** [comment]
v201 works gloriously, thanks a million.
