### ISSUE TITLE
Prepare release v229 (#1177) breaking changes?

### ISSUE THREAD

**Issue by circuitfinance** [heroku/heroku-buildpack-nodejs#1179]
**Describe the bug**
We host our api on Heroku and it was running fine until a few hours ago. I checked here and see it was just about the time that you merged the `Prepare release v229 (#1177)` branch.

I looked at the git log and don't see anything major that changed. So I'm wondering if anything else might have changed that caused the following. We've never seen this error before. Any idea why this would be occurring now?

```
2023-11-28T01:55:42.152557+00:00 heroku[web.1]: Starting process with command `npm start`
2023-11-28T01:55:42.897650+00:00 app[web.1]: 
2023-11-28T01:55:42.897672+00:00 app[web.1]: > circuit-finance-api@1.0.0 start
2023-11-28T01:55:42.897672+00:00 app[web.1]: > ts-node --transpile-only src/app.ts
2023-11-28T01:55:42.897672+00:00 app[web.1]: 
2023-11-28T01:55:43.357655+00:00 heroku[web.1]: Process exited with status 1
2023-11-28T01:55:43.273367+00:00 app[web.1]: /app/node_modules/ts-node/src/index.ts:859
2023-11-28T01:55:43.273390+00:00 app[web.1]:     return new TSError(diagnosticText, diagnosticCodes, diagnostics);
2023-11-28T01:55:43.273391+00:00 app[web.1]:            ^
2023-11-28T01:55:43.274760+00:00 app[web.1]: TSError: ⨯ Unable to compile TypeScript:
2023-11-28T01:55:43.274760+00:00 app[web.1]: error TS6053: File 'ts-node/node12/tsconfig.json' not found.
2023-11-28T01:55:43.274761+00:00 app[web.1]: 
2023-11-28T01:55:43.274761+00:00 app[web.1]:     at createTSError (/app/node_modules/ts-node/src/index.ts:859:12)
2023-11-28T01:55:43.274761+00:00 app[web.1]:     at reportTSError (/app/node_modules/ts-node/src/index.ts:863:19)
2023-11-28T01:55:43.274762+00:00 app[web.1]:     at createFromPreloadedConfig (/app/node_modules/ts-node/src/index.ts:874:36)
2023-11-28T01:55:43.274762+00:00 app[web.1]:     at phase4 (/app/node_modules/ts-node/src/bin.ts:543:44)
2023-11-28T01:55:43.274762+00:00 app[web.1]:     at bootstrap (/app/node_modules/ts-node/src/bin.ts:95:10)
2023-11-28T01:55:43.274763+00:00 app[web.1]:     at main (/app/node_modules/ts-node/src/bin.ts:55:10)
2023-11-28T01:55:43.274763+00:00 app[web.1]:     at Object.<anonymous> (/app/node_modules/ts-node/src/bin.ts:800:3)
2023-11-28T01:55:43.274763+00:00 app[web.1]:     at Module._compile (node:internal/modules/cjs/loader:1105:14)
2023-11-28T01:55:43.274764+00:00 app[web.1]:     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1159:10)
2023-11-28T01:55:43.274764+00:00 app[web.1]:     at Module.load (node:internal/modules/cjs/loader:981:32) {
2023-11-28T01:55:43.274764+00:00 app[web.1]:   diagnosticCodes: [ 6053 ]
2023-11-28T01:55:43.274765+00:00 app[web.1]: }
2023-11-28T01:55:43.378531+00:00 heroku[web.1]: State changed from starting to crashed
```

**To Reproduce**
Restarting our app

**Versions (please complete the following information):**
 - Heroku Stack: [`heroku-20`]
 - Node Version: [`16.1.0`]
 - NPM: [`NPM 8.11.0`]
 - Buildpack Version: [`heroku/nodejs`]

**Comment by colincasey** [comment]
@circuitfinance it's unlikely that the latest release broke your application.  The release only made newer versions of Node and Yarn available and based on your version information, you aren't using those.  

From the log you attached it looks like your build succeeded but the application failed to start because of a missing dependency (`ts-node/node12/tsconfig.json`).  Maybe the dependency was previously cached but then the cache was invalidated after your last build and now it's no longer there?  

You should confirm that either:
- the `ts-node` dependency is listed in your `"dependencies"` in `package.json` and not in `"devDependencies"` since dev dependencies are pruned at the end of the application's build process
- or the application runs with [pruning disabled](https://devcenter.heroku.com/articles/nodejs-support#skip-pruning)

If, after that, you're still having problems then please open a support ticket.
