### ISSUE TITLE
(node) warning: possible EventEmitter memory leak detected

### ISSUE THREAD

**Issue by bradoyler** [heroku/heroku-buildpack-nodejs#334]
with [v91](https://github.com/heroku/heroku-buildpack-nodejs/releases/tag/v91) of this buildpack I consistently get the error: 
```
 (node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
remote:        Trace
remote:        at TLSSocket.addListener (events.js:239:17)
remote:        at TLSSocket.Readable.on (_stream_readable.js:680:33)
remote:        at Request.<anonymous> (/tmp/build_b721959935eb9b988cb58f8b0b7afd04/.heroku/node/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:153:7)
remote:        at emitOne (events.js:77:13)
remote:        at Request.emit (events.js:169:7)
remote:        at ClientRequest.<anonymous> (/tmp/build_b721959935eb9b988cb58f8b0b7afd04/.heroku/node/lib/node_modules/npm/node_modules/request/request.js:791:10)
remote:        at emitOne (events.js:82:20)
remote:        at ClientRequest.emit (events.js:169:7)
remote:        at tickOnSocket (_http_client.js:502:7)
remote:        at onSocketNT (_http_client.js:514:5)
```

Error goes away if I revert back to v90

so my short-term solution was:
```
heroku buildpacks:set https://github.com/heroku/heroku-buildpack-nodejs#v90
```

**Comment by hunterloftis** [comment]
That's an error that comes from within node; has nothing to do with the buildpack.

**Comment by bradoyler** [comment]
@hunterloftis I understand where the warning comes from but this error appears during the heroku build process and only occurs with this buildpack. Just giving a heads...

**Comment by hunterloftis** [comment]
From a quick check, it looks like that's an issue with the combination of node and npm binaries the app is specifying:

```
v6.2.0:~/test/express (master)$ nvm install 4.4.7
######################################################################## 100.0%
Checksums empty
Now using node v4.4.7
v4.4.7:~/test/express (master)$ npm install -g npm@2.15.10
/Users/hloftis/.nvm/versions/node/v4.4.7/bin/npm -> /Users/hloftis/.nvm/versions/node/v4.4.7/lib/node_modules/npm/bin/npm-cli.js
npm@2.15.10 /Users/hloftis/.nvm/versions/node/v4.4.7/lib/node_modules/npm
v4.4.7:~/test/express (master)$ rm -rf node_modules/
v4.4.7:~/test/express (master)$ npm install
npm WARN deprecated jade@1.3.1: Jade has been renamed to pug, please install the latest version of pug instead of jade
npm WARN deprecated static-favicon@1.0.2: use serve-favicon module
npm WARN deprecated transformers@2.1.0: Deprecated, use jstransformer
(node) warning: possible EventEmitter memory leak detected. 11 error listeners added. Use emitter.setMaxListeners() to increase limit.
Trace
    at TLSSocket.addListener (events.js:239:17)
    at TLSSocket.Readable.on (_stream_readable.js:680:33)
    at Request.<anonymous> (/Users/hloftis/.nvm/versions/node/v4.4.7/lib/node_modules/npm/node_modules/npm-registry-client/lib/request.js:153:7)
    at emitOne (events.js:77:13)
    at Request.emit (events.js:169:7)
    at ClientRequest.<anonymous> (/Users/hloftis/.nvm/versions/node/v4.4.7/lib/node_modules/npm/node_modules/request/request.js:791:10)
    at emitOne (events.js:82:20)
    at ClientRequest.emit (events.js:169:7)
    at tickOnSocket (_http_client.js:502:7)
    at onSocketNT (_http_client.js:514:5)
```

**Comment by bradoyler** [comment]
Ok, thx. I narrowed it down to an issue with `npm@2.15.10`
changing engines.npm to `3.x` made the warning go away.

**Comment by hunterloftis** [comment]
One thing to consider is just removing the npm engine key - the version of npm bundled with a given version of the node binary is always the one most heavily tested (and most likely to work smoothly).

**Comment by jskrzypek** [comment]
@bradoyler I'm seeing the same issue. Have you reported this on npm?
