### ISSUE TITLE
yarn fails build

### ISSUE THREAD

**Issue by asimpson** [heroku/heroku-buildpack-nodejs#351]
PR apps are failing to build due to the error below:
```
-----> Node.js app detected
-----> Creating runtime environment
       
       NPM_CONFIG_LOGLEVEL=error
       NPM_CONFIG_PRODUCTION=true
       NODE_ENV=production
       NODE_MODULES_CACHE=true
-----> Installing binaries
       engines.node (package.json):  6.1.0
       engines.npm (package.json):   unspecified (use default)
       
       Downloading and installing node 6.1.0...
       Using default npm version: 3.8.6
       Resolving yarn version (latest) via semver.io...
       Downloading and installing yarn (0.17.10)...
       Installed yarn 0.17.10
-----> Restoring cache
       Skipping cache restore (new runtime signature)
-----> Building dependencies
       Installing node modules (yarn)
       yarn install v0.17.10
       [1/4] Resolving packages...
       [2/4] Fetching packages...
       warning fsevents@1.0.15: The platform "linux" is incompatible with this module.
       info "fsevents@1.0.15" is an optional dependency and failed compatibility check. Excluding it from installation.
       [3/4] Linking dependencies...
       warning Incorrect peer dependency "eslint-plugin-import@^1.16.0".
       warning Incorrect peer dependency "eslint-plugin-import@^1.16.0".
       [4/4] Building fresh packages...
       error phantomjs-prebuilt: Command failed.
       Exit code: 1
       Command: sh
       Arguments: -c node install.js
       Directory: node_modules/directory-colorfy/node_modules/phantomjs-prebuilt
       Output:
       module.js:440
       throw err;
       ^
       
       Error: Cannot find module 'bl'
       at Function.Module._resolveFilename (module.js:438:15)
       at Function.Module._load (module.js:386:25)
       at Module.require (module.js:466:17)
       at require (internal/module.js:20:19)
       at Object.<anonymous> (node_modules/directory-colorfy/node_modules/request/request.js:9:10)
       at Module._compile (module.js:541:32)
       at Object.Module._extensions..js (module.js:550:10)
       at Module.load (module.js:456:32)
       at tryModuleLoad (module.js:415:12)
       at Function.Module._load (module.js:407:3)
       info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
```

The buildpacks in use:

```
  "buildpacks": [
    { "url": "https://github.com/stomita/heroku-buildpack-phantomjs" },
    { "url": "https://github.com/heroku/heroku-buildpack-nodejs" }
  ]
```

I may be incorrectly assuming this is yarn related.

**Comment by hunterloftis** [comment]
It is yarn related, but the buildpack just got yarn support so this app was likely installing deps with npm before. Can you open a ticket so I can check out the app directly?

**Comment by joshmanders** [comment]
Yes this is a known issue in Yarn. https://github.com/yarnpkg/yarn/issues/2142

**Comment by hunterloftis** [comment]
I'd also recommend specifying in package.json (`engines.yarn`) the exact same version of yarn you're using locally to build the app.

**Comment by asimpson** [comment]
@hunterloftis support ticket opened.
