### ISSUE TITLE
"npm -v " throw new Error('npm.load() required')

### ISSUE THREAD

**Issue by haoyinag** [heroku/heroku-buildpack-nodejs#542]
: spawn C:\Program Files\nodejs\node.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:227:19)
    at onErrorNT (internal/child_process.js:404:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:721:11)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:576:3)
C:\Program Files\nodejs\node_modules\npm\lib\npm.js:61
      throw new Error('npm.load() required')
      ^

Error: npm.load() required
    at Object.get (C:\Program Files\nodejs\node_modules\npm\lib\npm.js:61:13)
    at process.errorHandler (C:\Program Files\nodejs\node_modules\npm\lib\utils\error-handler.js:205:18)
    at process.emit (events.js:182:13)
    at process._fatalException (internal/bootstrap/node.js:436:27)
5.6.0

events.js:167
      throw er; // Unhandled 'error' event
      ^

Error: spawn C:\Program Files\nodejs\node.exe ENOENT
    at Process.ChildProcess._handle.onexit (internal/child_process.js:227:19)
    at onErrorNT (internal/child_process.js:404:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
    at Function.Module.runMain (internal/modules/cjs/loader.js:721:11)
    at startup (internal/bootstrap/node.js:228:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:576:3)
Emitted 'error' event at:
    at Process.ChildProcess._handle.onexit (internal/child_process.js:233:12)
    at onErrorNT (internal/child_process.js:404:16)
    [... lines matching original stack trace ...]
    at bootstrapNodeJSCore (internal/bootstrap/node.js:576:3)

**Comment by jmorrell** [comment]
Hi there,

It looks like you're trying to use absolute Windows file paths from your local machine on your Heroku app? Heroku deploys your application into an Ubuntu environment, so you will need to use platform agnostic filesystem API's and relative paths.

Please file a support ticket at help.heroku.com, and we will try to help you, but this is not a buildpack issue.
