### ISSUE TITLE
Yarn 2 Qualified path resolution failed

### ISSUE THREAD

**Issue by CristianMR** [heroku/heroku-buildpack-nodejs#809]
Hi there,

I've been trying to get yarn 2 to work without luck.

Like in [this issue](https://github.com/yarnpkg/berry/issues/1567) I tried to add bcrypt built false into "dependenciesMeta" inside package.json but it continues to being unable to resolve the dependency.

```
Starting process with command `yarn node dist/server.js`
Process exited with status 1
State changed from starting to crashed
State changed from crashed to starting

/app/.pnp.js:20291
    throw firstError;
    ^

Error: Qualified path resolution failed - none of the candidates can be found on the disk.

Source path: /app/.yarn/unplugged/bcrypt-npm-5.0.0-b432f1b517/node_modules/bcrypt
Rejected candidate: /app/.yarn/unplugged/bcrypt-npm-5.0.0-b432f1b517/node_modules/bcrypt
Rejected candidate: /app/.yarn/unplugged/bcrypt-npm-5.0.0-b432f1b517/node_modules/bcrypt.js
Rejected candidate: /app/.yarn/unplugged/bcrypt-npm-5.0.0-b432f1b517/node_modules/bcrypt.json
Rejected candidate: /app/.yarn/unplugged/bcrypt-npm-5.0.0-b432f1b517/node_modules/bcrypt.node

Require stack:
- /app/.yarn/unplugged/bcrypt-npm-5.0.0-b432f1b517/node_modules/bcrypt/bcrypt.js
- /app/dist/models/User.js
- /app/dist/models/init.js
- /app/dist/app/mongoose.js
- /app/dist/app/index.js
- /app/dist/server.js
    at internalTools_makeError (/app/.pnp.js:20036:34)
    at resolveUnqualified (/app/.pnp.js:21037:13)
    at resolveRequest (/app/.pnp.js:21061:14)
    at Object.resolveRequest (/app/.pnp.js:21121:26)
    at Function.external_module_.Module._resolveFilename (/app/.pnp.js:20268:34)
    at Function.external_module_.Module._load (/app/.pnp.js:20132:48)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/app/.yarn/unplugged/bcrypt-npm-5.0.0-b432f1b517/node_modules/bcrypt/bcrypt.js:6:16)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.external_module_.Module._load (/app/.pnp.js:20164:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> (/app/dist/models/User.js:10:34)
    at Module._compile (internal/modules/cjs/loader.js:1138:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1158:10)
    at Module.load (internal/modules/cjs/loader.js:986:32)
    at Function.external_module_.Module._load (/app/.pnp.js:20164:14)
    at Module.require (internal/modules/cjs/loader.js:1026:19)
    at require (internal/modules/cjs/helpers.js:72:18)
```

**Comment by danielleadams** [comment]
Hi @CristianMR - this is expected. We're still in the process of figuring out what running `yarn install` will look like and are aware this affects packages with postinstall scripts. I'm going to mark this as a bug because this is high priority and hoping to have this sorted out soon. Thanks for raising this!
