### ISSUE TITLE
Getting concurrently when deploying a app on Heroku 

### ISSUE THREAD

**Issue by whizzbbig** [heroku/heroku-buildpack-nodejs#971]
**Describe the bug**
so I wanted to deploy a app which has express.js webpack technology its my first time and... its running concurrently

**To Reproduce**
1. Go to 'https://github.com/whizzbbig/floema_'
2. install all the dependencies setup your heroku and run this command `git push heroku main`
3. after downloading all the dependencies when you go to the app url you'll see application error
4. go to vs code terminal and pass this command `heroku logs --tail`
5. you'll see concurrently not found error where i not only installed it as dependency but also globally in home directory

**Versions (please complete the following information):**
 - Heroku Stack: latest
 - Node Version: v15.4.0
 - NPM or Yarn Version: 7.0.15
 - Buildpack Version: idk what it is

**Additional context**
```sh
2022-01-15T04:06:08.347021+00:00 heroku[web.1]: Starting process with command `npm start`
2022-01-15T04:06:09.630096+00:00 app[web.1]: 
2022-01-15T04:06:09.630112+00:00 app[web.1]: > floema@1.0.0 start /app
2022-01-15T04:06:09.630113+00:00 app[web.1]: > concurrently --kill-others "npm run backend:development" "npm run frontend:development"
2022-01-15T04:06:09.630113+00:00 app[web.1]: 
2022-01-15T04:06:09.635067+00:00 app[web.1]: sh: 1: concurrently: not found
2022-01-15T04:06:09.640773+00:00 app[web.1]: npm ERR! code ELIFECYCLE
2022-01-15T04:06:09.640928+00:00 app[web.1]: npm ERR! syscall spawn
2022-01-15T04:06:09.641051+00:00 app[web.1]: npm ERR! file sh
2022-01-15T04:06:09.641120+00:00 app[web.1]: npm ERR! errno ENOENT
2022-01-15T04:06:09.644758+00:00 app[web.1]: npm ERR! floema@1.0.0 start: `concurrently --kill-others "npm run backend:development" "npm run frontend:development"`
2022-01-15T04:06:09.644793+00:00 app[web.1]: npm ERR! spawn ENOENT
2022-01-15T04:06:09.644837+00:00 app[web.1]: npm ERR!
2022-01-15T04:06:09.644876+00:00 app[web.1]: npm ERR! Failed at the floema@1.0.0 start script.
2022-01-15T04:06:09.644910+00:00 app[web.1]: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
2022-01-15T04:06:09.649703+00:00 app[web.1]: 
2022-01-15T04:06:09.649775+00:00 app[web.1]: npm ERR! A complete log of this run can be found in:
2022-01-15T04:06:09.649810+00:00 app[web.1]: npm ERR!     /app/.npm/_logs/2022-01-15T04_06_09_645Z-debug.log
2022-01-15T04:06:09.753719+00:00 heroku[web.1]: Process exited with status 1
2022-01-15T04:06:09.949024+00:00 heroku[web.1]: State changed from starting to crashed
2022-01-15T04:06:07.000000+00:00 app[api]: Build succeeded
2022-01-15T04:06:15.687428+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/" host=floema-ice.herokuapp.com request_id=a666d803-8871-4eb0-ad76-3035ebd5e28a fwd="103.110.48.15" dyno= connect= service= status=503 bytes= protocol=https
2022-01-15T04:06:16.530299+00:00 heroku[router]: at=error code=H10 desc="App crashed" method=GET path="/favicon.ico" host=floema-ice.herokuapp.com request_id=7551b86f-dd7f-41d8-82ca-ec2a9e589df3 fwd="103.110.48.15" dyno= connect= service= status=503 bytes= protocol=https
```
the error  👆

**Comment by joshwlewis** [comment]
@whizzbbig Judging by the commits on the repo you linked, it looks like this is no longer an issue for you? In any case, this doesn't seem like a buildpack problem.

**Comment by whizzbbig** [comment]
> 

I able to fix this concurrently error now i am facing this error 
```sh
2022-02-08T09:08:59.411119+00:00 app[web.1]: [0] (node:100) UnhandledPromiseRejectionWarning: Error: A valid fetch implementation was not provided. In environments where fetch is not available (including Node.js), a fetch implementation must be provided via a polyfill or the `fetch` option.
2022-02-08T09:08:59.411130+00:00 app[web.1]: [0]     at new Client (/app/node_modules/@prismicio/client/dist/index.cjs:237:13)
2022-02-08T09:08:59.411130+00:00 app[web.1]: [0]     at Object.createClient (/app/node_modules/@prismicio/client/dist/index.cjs:214:35)
2022-02-08T09:08:59.411131+00:00 app[web.1]: [0]     at initApi (/app/app.js:29:18)
2022-02-08T09:08:59.411132+00:00 app[web.1]: [0]     at /app/app.js:130:21
2022-02-08T09:08:59.411132+00:00 app[web.1]: [0]     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2022-02-08T09:08:59.411133+00:00 app[web.1]: [0]     at next (/app/node_modules/express/lib/router/route.js:137:13)
2022-02-08T09:08:59.411134+00:00 app[web.1]: [0]     at Route.dispatch (/app/node_modules/express/lib/router/route.js:112:3)
2022-02-08T09:08:59.411134+00:00 app[web.1]: [0]     at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)
2022-02-08T09:08:59.411134+00:00 app[web.1]: [0]     at /app/node_modules/express/lib/router/index.js:281:22
2022-02-08T09:08:59.411135+00:00 app[web.1]: [0]     at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)
2022-02-08T09:08:59.411135+00:00 app[web.1]: [0] (Use `node --trace-warnings ...` to show where the warning was created)
2022-02-08T09:08:59.411168+00:00 app[web.1]: [0] (node:100) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
2022-02-08T09:08:59.415671+00:00 app[web.1]: [0] (node:100) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by whizzbbig** [comment]
and the repo i mentioned above wasn't using the heroku however i updated it with the private one. i am sending you the invitation of private repo please resolve the error 🙏🏻

**Comment by whizzbbig** [comment]
@joshwlewis yo problem haven't even solve please reopen the issue

**Comment by joshwlewis** [comment]
@whizzbbig This is an issue tracker for problems with the buildpack. I don't see a problem with the buildpack described here. I see what looks like an application issue. If you need support deploying your app to heroku, I'd suggest opening a ticket at help.heroku.com. But our support agents and I can't and won't fix your app for you. We can only provide tips and coaching (and this issue tracker is not the place).

Regarding this specific error: `UnhandledPromiseRejectionWarning: Error: A valid fetch implementation was not provided. In environments where fetch is not available (including Node.js), a fetch implementation must be provided via a polyfill or the `fetch` option.`: Node.js does not come with `fetch`. You'll have to provide it somehow. Most folks would bring in the `node-fetch` polyfill for this with something like `npm install node-fetch`.

**Comment by whizzbbig** [comment]
> @whizzbbig This is an issue tracker for problems with the buildpack. I don't see a problem with the buildpack described here. I see what looks like an application issue. If you need support deploying your app to heroku, I'd suggest opening a ticket at help.heroku.com. But our support agents and I can't and won't fix your app for you. We can only provide tips and coaching (and this issue tracker is not the place).
> 
> Regarding this specific error: `UnhandledPromiseRejectionWarning: Error: A valid fetch implementation was not provided. In environments where fetch is not available (including Node.js), a fetch implementation must be provided via a polyfill or the `fetch` option.`: Node.js does not come with `fetch`. You'll have to provide it somehow. Most folks would bring in the `node-fetch` polyfill for this with something like `npm install node-fetch`.

yeah i've installed it the version which supports cjs env haven't checked it yet but lets try
